#!/usr/bin/env bash
# Manual Testing Guide for 401 Error Fix

echo "=========================================="
echo "401 Unauthorized Error - Manual Test Guide"
echo "=========================================="
echo ""

echo "STEP 1: Start Backend Server"
echo "Command: cd backend && python app.py"
echo "Expected: Flask server running on http://localhost:5000"
echo ""

echo "STEP 2: Start Frontend Dev Server"
echo "Command: cd user && npm run dev"
echo "Expected: React app running on http://localhost:5173 (or similar)"
echo ""

echo "STEP 3: Open Browser DevTools"
echo "1. Press F12 to open DevTools"
echo "2. Go to 'Console' tab"
echo "3. Go to 'Network' tab (for seeing headers)"
echo ""

echo "STEP 4: Login Test"
echo "1. Navigate to Login page (http://localhost:5173/auth)"
echo "2. Enter credentials:"
echo "   Email: customer@test.com"
echo "   Password: Customer@123"
echo "3. Click Login button"
echo ""

echo "STEP 5: Verify Console Output"
echo "You should see logs like:"
echo "  ✓ Login successful, token stored in localStorage"
echo "  [API] POST /auth/login - Token attached (eyJhbG...)"
echo "  [API] GET /auth/profile - Token attached (eyJhbG...)"
echo ""

echo "STEP 6: Check localStorage"
echo "In DevTools > Storage > Local Storage > http://localhost:5173:"
echo "  - amma_token: (should have a long JWT string)"
echo "  - auth_provider: custom"
echo ""

echo "STEP 7: Navigate to User Profile"
echo "1. Click on Profile or Account"
echo "2. View the Dashboard tab"
echo "3. Check Console for:"
echo "  [API] GET /cart - Token attached"
echo "  Loading cart with token: eyJhbG..."
echo ""

echo "STEP 8: Check Network Requests"
echo "1. Go to Network tab in DevTools"
echo "2. Look for requests to /api/cart and /api/orders"
echo "3. Click on each request"
echo "4. In 'Headers' tab, scroll to 'Request Headers'"
echo "5. You should see:"
echo "  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...."
echo ""

echo "STEP 9: Verify No 401 Errors"
echo "✓ Cart loads successfully (status 200)"
echo "✓ Orders load successfully (status 200)"
echo "✓ Dashboard cards show order/cart info"
echo "✓ Console shows no 401 errors"
echo ""

echo "=========================================="
echo "Troubleshooting"
echo "=========================================="
echo ""
echo "If you still see 401 errors:"
echo ""
echo "1. Check if token is in localStorage:"
echo "   In Console: localStorage.getItem('amma_token')"
echo "   Should return a long JWT string, not null"
echo ""
echo "2. Check if token is being sent:"
echo "   In Network tab, click on /api/cart request"
echo "   Look at 'Request Headers' for 'Authorization' header"
echo "   Should be: 'Authorization: Bearer <token>'"
echo ""
echo "3. Check API logs:"
echo "   Backend console should show:"
echo "   [INFO] GET /api/cart - User #28 (or similar)"
echo ""
echo "4. Verify backend is running:"
echo "   curl http://localhost:5000/api/health"
echo "   Should return: {\"status\":\"healthy\",...}"
echo ""
echo "5. Check for errors in DevTools Console:"
echo "   Look for red error messages with 401 details"
echo "   [API] Error 401: Unauthorized - ..."
echo ""

echo "=========================================="
echo "Expected Success Criteria"
echo "=========================================="
echo ""
echo "✅ Login with customer@test.com / Customer@123"
echo "✅ Token stored in localStorage['amma_token']"
echo "✅ Authorization header sent with every request"
echo "✅ /api/cart returns 200 with cart items"
echo "✅ /api/orders returns 200 with orders list"
echo "✅ /api/auth/profile returns 200 with user info"
echo "✅ No 401 errors in console"
echo "✅ No 401 errors in Network tab"
echo ""
