"""Add profile completed columns

Revision ID: 14ceb54fbee7
Revises: cc05d45bc485
Create Date: 2026-05-31 15:07:32.856329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ceb54fbee7'
down_revision = 'cc05d45bc485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('door_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('street_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('landmark', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_mobile', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preference', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preference')
        batch_op.drop_column('alternate_mobile')
        batch_op.drop_column('landmark')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('area')
        batch_op.drop_column('street_name')
        batch_op.drop_column('door_number')
        batch_op.drop_column('profile_completed')

    # ### end Alembic commands ###
